name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - react
        - html
        - create-build-stack

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install workspace dependencies
      run: |
        cd packages/react && npm install
        cd ../html && npm install  
        cd ../create-build-stack && npm install
        
    - name: Build all packages
      run: |
        npm run build:react
        npm run build:html
        npm run build:scaffolder
        
    - name: Publish React package
      if: ${{ github.event.inputs.package == 'all' || github.event.inputs.package == 'react' || github.event_name == 'release' }}
      run: |
        cd packages/react
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Publish HTML package
      if: ${{ github.event.inputs.package == 'all' || github.event.inputs.package == 'html' || github.event_name == 'release' }}
      run: |
        cd packages/html
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Publish Create Build Stack package
      if: ${{ github.event.inputs.package == 'all' || github.event.inputs.package == 'create-build-stack' || github.event_name == 'release' }}
      run: |
        cd packages/create-build-stack
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create success comment
      if: success()
      run: |
        echo "✅ Successfully published packages to NPM!"
        echo "📦 Published packages:"
        if [[ "${{ github.event.inputs.package }}" == "all" || "${{ github.event.inputs.package }}" == "react" || "${{ github.event_name }}" == "release" ]]; then
          echo "  - @build-stack/react"
        fi
        if [[ "${{ github.event.inputs.package }}" == "all" || "${{ github.event.inputs.package }}" == "html" || "${{ github.event_name }}" == "release" ]]; then
          echo "  - @build-stack/html" 
        fi
        if [[ "${{ github.event.inputs.package }}" == "all" || "${{ github.event.inputs.package }}" == "create-build-stack" || "${{ github.event_name }}" == "release" ]]; then
          echo "  - create-build-stack"
        fi